### ISSUE TITLE
Testimonial Page - Research button/tab via sidebar not implemented

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Sound-for-Life#32]
![image](https://cloud.githubusercontent.com/assets/12791909/12381939/ace883d2-bdce-11e5-824e-12c0ba79ae22.png)

**Comment by asif-titan** [comment]
I have forwarded you the email conversations between, Jolene, Andrew, Carin and Salman regarding clarity on the issue.
Thanks

**Comment by asif-titan** [comment]
As per Andrews Email :
Hi Salman,
 
Thanks for reaching out. I looked over the PSDs and the additional page link on the right hand side-bar seems counter-intuitive and unnecessary.
Feel free to go ahead and remove it in implementation.
 
Regards,
Andrew Hill | Front-End Developer – Cape Town

This applies to testimonial page too.

![getfileattachment](https://cloud.githubusercontent.com/assets/13450796/12758994/dbac7ce0-ca04-11e5-9cb8-190a3d957ed9.png)
