### ISSUE TITLE
Homepage - Testimonial featured image not displayed on the homepage.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Sound-for-Life#8]
![image](https://cloud.githubusercontent.com/assets/12791909/12316428/6dfac0e6-bac1-11e5-8f5f-55337b01838b.png)

**Comment by asif-titan** [comment]
I have forwarded you the email conversations between, Jolene, Andrew, Carin and Salman regarding clarity on the issue.
Thanks
